package FarmModel.ObjectInMap15_15.AnimalProductAndWorkShopProduct.AnimalsProduct;

import FarmModel.ObjectInMap15_15.AnimalProductAndWorkShopProduct.AnimalProductAndWorkShopProduct;

public  class AnimalsProduct extends AnimalProductAndWorkShopProduct {


}
