package FarmModel.ObjectOutOfMap15_15ButInTheBorderOfPlayGround.Vehicle;

import FarmModel.ObjectOutOfMap15_15ButInTheBorderOfPlayGround.ObjectOutOfMap15_15ButInTheBorderOfPlayGround;

public class TransportationVehicle extends ObjectOutOfMap15_15ButInTheBorderOfPlayGround {
    private double TimeToMoveThePath;
}
